# Generated by Django 5.2.3 on 2025-07-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (must be unique)', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when category was last updated')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
    ]
