# Generated by Django 5.2.3 on 2025-07-02 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title or description', max_length=200)),
                ('due_date', models.DateField(blank=True, help_text='When the task is due (optional)', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Task completion status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when task was last updated')),
                ('category', models.ForeignKey(help_text='Category this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.category')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['due_date', 'created_at'],
                'indexes': [models.Index(fields=['due_date'], name='tasks_task_due_dat_bce847_idx'), models.Index(fields=['completed'], name='tasks_task_complet_1ed563_idx'), models.Index(fields=['completed', 'due_date'], name='tasks_task_complet_ba75e8_idx')],
            },
        ),
    ]
